version: '3.5'

x-db-env:
  &db-login-data
  POSTGRES_MULTIPLE_DATABASES: "chainlink_dev,qtum_initiator,qtumtx_adapter"
  POSTGRES_PASSWORD: chainlink

services:
  janus:
    image: qtum/janus:dev
    build: 
        context: ./docker/standalone/
        cache_from:
          - golang:1.14-alpine
          - qtum/janus:dev
    ports:
        - "23889:23889"
    environment: 
        - QTUM_RPC=http://qtum:testpasswd@qtum:3889
    volumes:
        - ./docker/standalone/myaccounts.txt:/go/myaccounts.txt
    depends_on:
      - qtum
    command: --bind 0.0.0.0 --accounts myaccounts.txt --dev
  qtum:
    container_name: qtum
    ports:
      - "3889:3889"
      - "3890:3890"
    image: qtum/qtum:latest
    command: qtumd -regtest  -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 -logevents -rpcuser=qtum -rpcpassword=testpasswd -deprecatedrpc=accounts -printtoconsole
  postgres-server:
    container_name: postgres-server
    build: ./docker/postgres-server
    environment: *db-login-data
    ports:
      - 5433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
  chainlink-node:
    container_name: chainlink-node
    build: ./docker/chainlink-node
    depends_on:
      - postgres-server
    environment: *db-login-data
    env_file:
      - ./docker/chainlink-node/.env
    links:
      - "postgres-server"
    ports:
      - 6688:6688
    secrets:
      - chainlink_secret
      - chainlink_api
      - chainlink_key
  qtum-initiator:
    container_name: qtum-initiator
    build:
      context: .
      dockerfile: ./qtum-initiator/Dockerfile
    env_file:
      - ./qtum-initiator/.env
    depends_on:
      - qtum
    links:
      - "qtum"
    ports:
      - 30055:30055
    secrets:
      - source: chainlink_api
        target: /home/qtum-initiator/src/.api
    volumes:
      - ./qtum-initiator/src:/home/qtum-initiator/src
      - ./chainlink-api-client/src:/home/chainlink-api-client/src
      - initiator-modules:/home/qtum-initiator/node_modules
      - chainlink-api-client-modules:/home/chainlink-api-client/node_modules
      - shared-volume:/home/qtum-initiator/config
  qtumtx-adapter:
    container_name: qtumtx-adapter
    build:
      context: .
      dockerfile: ./qtumtx-adapter/Dockerfile
    env_file:
      - ./qtumtx-adapter/.env
    depends_on:
      - qtum
    links:
      - "qtum"
    ports:
      - 30056:30056
    # secrets:
      # - adapter_key
      # - source: chainlink_api
      #   target: /home/qtumtx-adapter/src/.api
    volumes:
      - ./qtumtx-adapter/src:/home/qtumtx-adapter/src
      - ./chainlink-api-client/src:/home/chainlink-api-client/src
      - adapter-modules:/home/qtumtx-adapter/node_modules
      - chainlink-api-client-modules:/home/chainlink-api-client/node_modules
      - shared-volume:/home/qtumtx-adapter/config
secrets:
  # Janus derives a copy of private keys from your public key in it's current state, thus the adapterKey is futile.
  # adapter_key:
  #   file: ./qtumtx-adapter/src/.adapterKey
  chainlink_secret:
    file: ./docker/chainlink-node/.secret
  chainlink_api:
    file: ./docker/chainlink-node/.api
  chainlink_key:
    file: ./docker/chainlink-node/keystore.json
volumes:
  adapter-modules:
  contracts-build-directory:
  chainlink-api-client-modules:
  db-data:
  geth-db-data:
  initiator-modules:
  qtum-db-data:
  runner-modules:
  shared-volume:
